# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@aws-cdk/assert"
      - dependency-name: "@types/jest"
      - dependency-name: "@types/node"
      - dependency-name: "@types/puppeteer"
      - dependency-name: "aws-cdk-lib"
      - dependency-name: "constructs"
      - dependency-name: "jest"
      - dependency-name: "puppeteer-lambda"
      - dependency-name: "ts-jest"
      - dependency-name: "typescript"
